runtime: python39
entrypoint: gunicorn -b :$PORT app:app

#env_variables:
#  SECRET_KEY: "****"
#  CLOUD_SQL_CONNECTION_NAME: "cloudsql/storyverse-385315:europe-central2:storyverse"
#  #DB_HOST: "127.0.0.1"
#  DB_PORT: "5432"
#  DB_USER: "postgres"
#  DB_PASS: "******"
#  DB_NAME: "storyverse"