version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ******
      POSTGRES_DB: storyverse
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    # build: .
    image: swe-573-web
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
