version: '3.1'

services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ******
