runtime: python39
entrypoint: gunicorn app:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  SECRET_KEY: "****"
  INSTANCE_UNIX_SOCKET: "/cloudsql/storyverse-385315:europe-central2:storyverse"
  DB_USER: "postgres"
  DB_PASS: "******"
  DB_NAME: "storyverse"

handlers:
  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico

  - url: /static
    static_dir: static

  - url: /.*
    script: auto