"""Add lat_lon column to posts table

Revision ID: 98538bc27652
Revises: c58809ea7173
Create Date: 2023-05-21 22:37:37.219197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98538bc27652'
down_revision = 'c58809ea7173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat_lon', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('lat_lon')

    # ### end Alembic commands ###
